blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/poblabs/weewx-belchertown/discussions/categories/q-a
    about: Please ask and answer questions here.
